baseURL = 'https://tbwright.dev/'
languageCode = 'en-us'
title = 'tbwright.dev'
theme = 'congo'

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

# [outputs]
#   home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[params]
  enableSearch = true
  enableCodeCopy = true
  enableImageLazyLoading = true
  enableImageWebp = true

  colorScheme = "congo"
  defaultAppearance = "light" # valid options: light or dark
  autoSwitchAppearance = true

  defaultThemeColor = "#FFFFFF"

  fingerprintAlgorithm = "sha256"

  [params.homepage]
    layout = "profile"
    showRecent = true
    recentLimit = 5

  [params.footer]
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = false
    showScrollToTop = true

  [params.author]
    # Author details for profile layout
    name = "Tyler Wright"
    image = "headshot.jpeg"
    headline = "Lead Software Engineer @ CareerTEAM"
    links = [
      { email = "mailto:tyler@twright.tech" },
      { dev = "https://devpost.com/tbwrigh" },
      { github = "https://github.com/tbwrigh" },
      { linkedin = "https://linkedin.com/in/tyler-wright96" },
    ]
  
  [params.article]
    showAuthor = true
    showDate = true
    showReadingTime = true
    showShareButtons = true
    showTableOfContents = true
    enableCodeCopy = true

[menus]
  [[menus.main]]
    name = "Posts"
    url = "/posts"
    weight = 10

  # [[menus.main]]
  # name = "Categories"
  # pageRef = "categories"
  # weight = 20

  # [[menus.main]]
  # name = "Tags"
  # pageRef = "tags"
  # weight = 30

  [[menus.main]]
    identifier = "search"
    weight = 99

  [menus.main.params]
    action = "search"

  [[menus.main]]
  identifier = "locale"
  weight = 100

  [main.params]
    action = "locale"

  # -- Footer Menu --
  # The footer menu is displayed at the bottom of the page, just before
  # the copyright notice. Configure as per the main menu above.

  # [[menus.footer]]
  #   name = "Tags"
  #   pageRef = "tags"
  #   weight = 10
